name: Cypress Tests

on:
  push:
    branches:
      - main
  schedule:
        - cron: '0 0 * * 1/2'
  workflow_dispatch: # Enable the run worklfow button on the Action

jobs:
  setup-and-run-tests:
    name: Setup the environment and run the tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run Cypress tests
      run: npm run test

    - name: Generate test report
      run: npm run after-test

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./cypress/reports